### ISSUE TITLE
Handling celsius, v_init and template name

### ISSUE THREAD

**Issue by appukuttan-shailesh** [KaliLab/hippounit#11]
@sasaray : For the BluePyOpt optimized models `ModelLoader_BPO`, I believe, we are currently hard-coding the values of `celsius`, `v_init` and the `template_name`. (Let me know if I got this wrong). Probably some of this (`celsius`?) remains constant always for the models we are currently handling, and thus this might be reasonable to do.

But I was thinking it might be a good idea to pick these values up from the model's files itself. I am doing something along these lines for another module ([see here](https://github.com/appukuttan-shailesh/eFELunit/blob/master/eFELunit/utils.py#L40)), and we could adopt the same code here. Let me know what you think of this.

**Comment by sasaray** [comment]
@appukuttan-shailesh : Good idea. I start adopting your code.

**Comment by appukuttan-shailesh** [comment]
Great! Closing this issue... resolved in #12 .
