### ISSUE TITLE
Making HippoUnit compatible with Python 3

### ISSUE THREAD

**Issue by appukuttan-shailesh** [KaliLab/hippounit#20]
Low priority task.... but we should probably convert all `print` statements to be compatible with Python 3.
So lets change all:
`print "message"`
to 
`print ("message")`

**Comment by appukuttan-shailesh** [comment]
@sasaray : Since Python 2 is going to be officially retired in January 2020, we should ensure that HippoUnit is Python 3 compatible. One of the (simpler) changes is changing the print statements as indicated in above post.

**Comment by sasaray** [comment]
@appukuttan-shailesh : I made HippoUnit Python 3 compatible (and kept Python 2 compatibility). I added a new version number of 1.3. Shall I make it pip installable?

**Comment by appukuttan-shailesh** [comment]
That would be useful. If you could then update the hippounit use case to make use of this latest version (first cell of notebook I think), we can have Alex test it to confirm that it works well on both Py2 and Py3.

p.s. I am away on vacations from tonight but expect to be reachable via emails.
